dataset=hipe2020
lang=fr
batchsize=1

#TOKENIZERS_PARALLELISM=false python main.py  --directory ../runs/"$dataset"-"$lang"-2T-multilingual-sent-mean-PAPER-multi-1 --pre_trained_model bert-base-multilingual-cased --train_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/HIPE-2022-v2.1-"$dataset"-train-"$lang".tsv  --test_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/HIPE-2022-v2.1-"$dataset"-test-ELmasked-"$lang".tsv  --dev_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/HIPE-2022-v2.1-"$dataset"-dev-"$lang".tsv  --do_train  --no_cpu 5 --language english --model stacked --num_layers 2 --n_heads 12 --head_dims 128 --trans_dropout 0.45 --fc_dropout 0.4 --pos_embed sin --batch_size "$batchsize" --n_epochs 10
#TOKENIZERS_PARALLELISM=false python main.py  --directory ../runs/"$dataset"-"$lang"-2T-multilingual-sent-mean-v0-PAPER-multi-1 --pre_trained_model bert-base-multilingual-cased --train_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/hipe_doc_full_wiki_v0/train_all.txt  --test_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/hipe_doc_full_wiki_v0/test.txt  --dev_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/hipe_doc_full_wiki_v0/dev.txt  --do_train  --no_cpu 5 --language english --model stacked --num_layers 2 --n_heads 12 --head_dims 128 --trans_dropout 0.45 --fc_dropout 0.4 --pos_embed sin --batch_size "$batchsize" --n_epochs 10
#TOKENIZERS_PARALLELISM=false python main.py  --directory ../runs/"$dataset"-"$lang"-2T-multilingual-sent-mean-v1-PAPER-multi-1 --pre_trained_model bert-base-multilingual-cased --train_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/hipe_doc_full_wiki_v1/train_all.txt  --test_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/hipe_doc_full_wiki_v1/test.txt  --dev_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/hipe_doc_full_wiki_v1/dev.txt  --do_train  --no_cpu 5 --language english --model stacked --num_layers 2 --n_heads 12 --head_dims 128 --trans_dropout 0.45 --fc_dropout 0.4 --pos_embed sin --batch_size "$batchsize" --n_epochs 10
#TOKENIZERS_PARALLELISM=false python main.py  --directory ../runs/"$dataset"-"$lang"-2T-multilingual-sent-mean-v2-PAPER-multi-1 --pre_trained_model bert-base-multilingual-cased --train_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/hipe_doc_full_wiki_v2/train_all.txt  --test_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/hipe_doc_full_wiki_v2/test.txt  --dev_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/hipe_doc_full_wiki_v2/dev.txt  --do_train  --no_cpu 5 --language english --model stacked --num_layers 2 --n_heads 12 --head_dims 128 --trans_dropout 0.45 --fc_dropout 0.4 --pos_embed sin --batch_size "$batchsize" --n_epochs 10
#TOKENIZERS_PARALLELISM=false python main.py  --directory ../runs/"$dataset"-"$lang"-2T-multilingual-sent-mean-v3-PAPER-multi-1 --pre_trained_model bert-base-multilingual-cased --train_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/hipe_doc_full_wiki_v3/train_all.txt  --test_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/hipe_doc_full_wiki_v3/test.txt  --dev_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/hipe_doc_full_wiki_v3/dev.txt  --do_train  --no_cpu 5 --language english --model stacked --num_layers 2 --n_heads 12 --head_dims 128 --trans_dropout 0.45 --fc_dropout 0.4 --pos_embed sin --batch_size "$batchsize" --n_epochs 10
TOKENIZERS_PARALLELISM=false python main.py  --directory ../runs/"$dataset"-"$lang"-2T-multilingual-sent-mean-v4-PAPER-multi-1 --pre_trained_model bert-base-multilingual-cased --train_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/hipe_doc_full_wiki_v4/train_all.txt  --test_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/hipe_doc_full_wiki_v4/test.txt  --dev_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/hipe_doc_full_wiki_v4/dev.txt  --do_train  --no_cpu 5 --language english --model stacked --num_layers 1 --n_heads 12 --head_dims 128 --trans_dropout 0.45 --fc_dropout 0.4 --pos_embed sin --batch_size "$batchsize" --n_epochs 10
#TOKENIZERS_PARALLELISM=false python main.py  --directory ../runs/"$dataset"-"$lang"-2T-multilingual-sent-mean-v5-PAPER-multi-1 --pre_trained_model bert-base-multilingual-cased --train_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/hipe_doc_full_wiki_v5/train_all.txt  --test_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/hipe_doc_full_wiki_v5/test.txt  --dev_dataset ../KB-NER/kb/datasets/"$dataset"/"$lang"/hipe_doc_full_wiki_v5/dev.txt  --do_train  --no_cpu 5 --language english --model stacked --num_layers 2 --n_heads 12 --head_dims 128 --trans_dropout 0.45 --fc_dropout 0.4 --pos_embed sin --batch_size "$batchsize" --n_epochs 10
